from enum import Enum

class ErrorStatus(Enum):
    LARGE_AMOUNT_REFUND = 0
    SUSPICIOUS_ACTIVITY = 1
    STATUS_MISMATCH = 2
    LARGE_VOLUME_TRANSACTION_TO_FINALIZE = 3
    QUERY_RESULT_THIRD_PARTY_TRANSACTION_DIFFENCE_LARGER_THAN_USUAL = 4
    THIRD_PARTY_TOTAL_AMOUNT_MISMATCH = 5
    LARGE_VOLUME_BILL_NO_NOT_SUCCESSFUL = 6
    PREVIOUS_NEXT_DAY_AMOUNT_MISMATCH = 7
    UNABLE_TO_PREPROCESS_DATA = 8
    DUPLICATE_IN_DATASETS = 9
    MISSING_DATE_FROM_DATASETS = 10